# Generated by Django 5.2.7 on 2025-10-31 17:30

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_add_product_label_and_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='income',
        ),
        migrations.AddField(
            model_name='customer',
            name='education',
            field=models.CharField(blank=True, choices=[('HS', 'High School'), ('DP', 'Diploma'), ('BD', 'Bachelor'), ('MS', 'Master'), ('DR', 'Doctorate')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('FT', 'Full-time'), ('PT', 'Part-time'), ('SE', 'Self-employed'), ('ST', 'Student')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='has_children',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='household_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='monthly_income',
            field=models.CharField(blank=True, choices=[('0-2000', '$0 - $2,000'), ('2001-4000', '$2,001 - $4,000'), ('4001-6000', '$4,001 - $6,000'), ('6001-8000', '$6,001 - $8,000'), ('8001-10000', '$8,001 - $10,000'), ('10001+', 'Above $10,000')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_categories',
            field=models.CharField(blank=True, help_text='Comma-separated list of 3 preferred categories', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Unique product identifier', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/adminpanel/images/', location='/Users/eleanorcheak/Desktop/IS2108 Pair Project/AuroraMart/auroramartproj/adminpanel/static/adminpanel/images'), upload_to=''),
        ),
    ]
