# Generated by Django 5.2.7 on 2025-10-31 17:44

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_remove_customer_income_customer_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/adminpanel/images/', location='/Users/seansee/Desktop/IS2108/auroramart/auroramartproj/adminpanel/static/adminpanel/images'), upload_to=''),
        ),
    ]
