# Generated by Django 5.2.7 on 2025-11-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_make_product_sku_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average rating imported from catalogue', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_threshold',
            field=models.PositiveIntegerField(blank=True, help_text='Reorder point imported from catalogue', null=True),
        ),
    ]
