# Generated by Django 5.2.7 on 2025-11-09 18:02

from django.db import migrations, models


CATEGORY_REMAP = {
    'electronics': 'electronics',
    'electronic': 'electronics',
    'hair': 'beauty_personal_care',
    'beauty': 'beauty_personal_care',
    'beauty_personal_care': 'beauty_personal_care',
    'beauty & personal care': 'beauty_personal_care',
    'personal care': 'beauty_personal_care',
    'fashion': 'fashion_women',
    'fashion_men': 'fashion_men',
    'fashion_women': 'fashion_women',
    'men': 'fashion_men',
    'women': 'fashion_women',
    'sports': 'sports_outdoors',
    'sports_outdoors': 'sports_outdoors',
    'sports & outdoors': 'sports_outdoors',
    'home': 'home_kitchen',
    'home_kitchen': 'home_kitchen',
    'home & kitchen': 'home_kitchen',
    'books': 'books',
    'groceries': 'groceries_gourmet',
    'groceries_gourmet': 'groceries_gourmet',
    'groceries & gourmet': 'groceries_gourmet',
    'toys': 'toys_games',
    'toys_games': 'toys_games',
    'toys & games': 'toys_games',
    'others': 'other',
    'other': 'other',
    'automotive': 'automotive',
    'auto': 'automotive',
    'vehicle': 'automotive',
    'health': 'health',
    'pet_supplies': 'pet_supplies',
    'pets': 'pet_supplies',
}


def _migrate_categories(apps, schema_editor):
    Product = apps.get_model('adminpanel', 'Product')
    for product in Product.objects.all():
        raw = (product.category or '').strip()
        lookup = raw.lower()
        target = CATEGORY_REMAP.get(lookup, raw)
        if target != product.category:
            Product.objects.filter(pk=product.pk).update(category=target)


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_product_rating_product_reorder_threshold_and_more'),
    ]

    operations = [
        migrations.RunPython(_migrate_categories, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('automotive', 'Automotive'), ('beauty_personal_care', 'Beauty & Personal Care'), ('books', 'Books'), ('electronics', 'Electronics'), ('fashion_men', 'Fashion - Men'), ('fashion_women', 'Fashion - Women'), ('groceries_gourmet', 'Groceries & Gourmet'), ('health', 'Health'), ('home_kitchen', 'Home & Kitchen'), ('pet_supplies', 'Pet Supplies'), ('sports_outdoors', 'Sports & Outdoors'), ('toys_games', 'Toys & Games'), ('other', 'Other')], max_length=100),
        ),
    ]
