# Generated by Django 5.2.7 on 2025-11-10 04:18

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/adminpanel/images/', location='/Users/eleanorcheak/Desktop/IS2108 Pair Project/AuroraMart/auroramartproj/adminpanel/static/adminpanel/images'), upload_to=''),
        ),
    ]
