# Generated by Django 5.2.7 on 2026-01-21 14:16

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/adminpanel/images/', location='/Users/seansee/Documents/GitHub/AuroraMart/auroramartproj/adminpanel/static/adminpanel/images'), upload_to=''),
        ),
    ]
